name: CI

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
